Add create audio speech stream support
MacPaw/OpenAI pull request #188
Opened 2024-03-27 14:09 UTC by batanus

## What

OpenAI supports sending audio speech by chunks (see my issue here: https://github.com/MacPaw/OpenAI/issues/185). This PR adds support for this feature.

## Why

With this change, clients can start audio playback with less latency, as far as first audio chunk will be received. 

## Affected Areas

In `OpenAIProtocol` was added new method `audioCreateSpeechStream`

2024-03-30 01:25 UTC, SunburstEnzo requested changes
Thanks for the PR! 😊 Minor things really; don't forget to update the readme either!

2024-03-30 01:25 UTC, SunburstEnzo commented on Sources/OpenAI/OpenAI.swift
> +
Extra line not needed

2024-03-30 01:25 UTC, SunburstEnzo commented on Sources/OpenAI/OpenAI.swift
> +            session.onReceiveContent = {_, object in
```suggestion
            session.onReceiveContent = { _, object in
```

2024-03-30 01:25 UTC, SunburstEnzo commented on Sources/OpenAI/OpenAI.swift
> +            session.onProcessingError = {_, error in
```suggestion
            session.onProcessingError = { _, error in
```

2024-03-30 01:25 UTC, SunburstEnzo commented on Sources/OpenAI/Public/Protocols/OpenAIProtocol+Async.swift
> +            return audioCreateSpeechStream(query: query)  { result in
```suggestion
            return audioCreateSpeechStream(query: query) { result in
```

2024-03-30 01:25 UTC, SunburstEnzo commented on Sources/OpenAI/Public/Protocols/OpenAIProtocol.swift
> +     openAI.audioCreateSpeech(query: query) { result in
```suggestion
     openAI.audioCreateSpeechStream(query: query) { result in
```
Don't forget to change the docs

2024-03-30 21:10 UTC, batanus commented
@SunburstEnzo Thanks for the comments! PR updated

2024-04-02 13:57 UTC, batanus commented
Closing this PR as new PR with the same changes was opened:
- https://github.com/MacPaw/OpenAI/pull/189

2024-04-02 13:57 UTC, closed without merging