Custom http headers
MacPaw/OpenAI pull request #93
Opened 2023-07-30 04:16 UTC by benvolioT

## What

This pull request adds the ability to specify custom HTTP headers when integrating with OpenAI via proxy APIs such as Helicone. It also refactors OpenAi's performRequest() by encapsulating the logic for handling the session data task in its own class, URLSessionDataTaskManager. This should simplify the OpenAI class and make the code easier to manage. This pull request simplifies JSONRequest and MultipartFormDataRequest by abstracting out common code to remove repetition that previously existed in these structs. Finally, it simplifies the protocol URLRequestBuildable, moving configuration-driven parameter setting to the constructors of these struct instances, rather than in the call to that protocol's build() function.

## Why

The motivation for this change was to allow users to integrate with OpenAI via the Helicone proxy. To do so, they not only need to point the OpenAI client at the Helicone host, but they also have to set an additional HTTP header on the requests. This pull request makes that possible.

## Affected Areas

The affected areas of the library include:

* The OpenAI class within the OpenAI.swift file.
* The client configuration within the constructor of the OpenAI class.
* The construction of requests in the following methods: completions(), completionsStream(), images(), embeddings(), chats(), chatsStream(), edits(), model(), models(), moderations(), audioTranscriptions(), and audioTranslations().

2023-08-19 17:08 UTC, benvolioT commented
Hi! Is there anything more I need to do in order to get this merged?

2023-08-22 11:05 UTC, Krivoblotsky commented
Hey, @benvolioT!
Thanks a lot for the contribution!
Please fix [build](https://github.com/MacPaw/OpenAI/actions/runs/5780727325/job/16100876240?pr=93) and merge conflicts 🙏

2023-08-22 11:29 UTC, Krivoblotsky commented on Sources/OpenAI/Private/StreamingSession.swift
> +        accumulatedData.append(stringContent)
Could you extract this change to a separate PR, please?
Looks like this is a separate fix, that doesn't apply to custom headers.

2023-08-22 11:32 UTC, Krivoblotsky commented on Sources/OpenAI/OpenAI.swift
> +    internal func generateHeaders() -> [String: String] {
I would change the naming to `defaultHeaders` to add the knowledge that it is going to be appended further. 
What do you think?

2023-08-22 11:34 UTC, Krivoblotsky requested changes
Overall looks good to me, thanks for the contribution!
1. Please fix the build. 
2. Fix merge conflicts
3. Extract `StreamingSession` fix into a separate PR.
Thanks!

2025-03-12 08:04 UTC, closed without merging

2025-03-12 08:04 UTC, nezhyborets commented
Thanks for the contribution @benvolioT ! The lib has drifted away a bit by merging other PRs and working on issues, and `customHeaders` were implemented as part of that work, see https://github.com/MacPaw/OpenAI/pull/263